s="Tops Tecnology"
print(s)
print(s.capitalize())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.center(40,"*"))
print(s.endswith("es"))
print(s.find("log"))
print(s.index("T",2))
print("tops123".isalnum())
print("tops".isalnum())
print("123".isalnum())
print("tops 123".isalnum())
print(" ".isspace())
print(s.istitle())
print("ToOPS".isupper())
print("tops".islower())
print(s.swapcase())
print("Pyton Programming".title())
print("Hello".replace("1","w"))      
      
